import { Box, Typography, Grid, Stack } from "@mui/material";
import { Star, LocationOn, Info, Verified } from "@mui/icons-material";
import type { SummarySectionProps } from "./SummarySection.types";

export const SummarySection: React.FC<SummarySectionProps> = ({ hotel }) => {
  return (
    <Box sx={{ mb: 12 }}>
      {/* HEADER */}
      <Stack spacing={2} mb={4}>
        <Stack direction="row" spacing={1} alignItems="center">
          {/* Stars */}
          <Box sx={{ display: "flex", color: "#facc15" }}>
            {Array.from({ length: hotel.starRating }).map((_, i) => (
              <Star key={i} sx={{ width: 20, height: 20 }} />
            ))}
          </Box>

          <Typography
            sx={{
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: 2,
              color: "text.secondary",
              textTransform: "uppercase",
            }}
          >
            Verified Luxury
          </Typography>
        </Stack>

        <Typography
          variant="h2"
          sx={{
            fontWeight: 900,
            fontSize: { xs: "2rem", md: "3rem", lg: "3.5rem" },
          }}
        >
          {hotel.name}
        </Typography>

        <Stack direction="row" spacing={1} alignItems="center">
          <LocationOn sx={{ color: "#2563eb", width: 20, height: 20 }} />
          <Typography fontWeight={500} color="text.primary">
            {hotel.location}
          </Typography>
        </Stack>
      </Stack>

      {/* DESCRIPTION + AI SUMMARY */}
      <Grid
        container
        spacing={4}
        sx={{ bgcolor: "#f1f5f9", p: 4, borderRadius: 4 }}
      >
        {/* Left: Hotel Description */}
        <Grid size={{ xs: 12, md: 6 }}>
          <Typography
            variant="h6"
            sx={{
              fontWeight: 700,
              mb: 2,
              display: "flex",
              alignItems: "center",
              color: "#2563eb",
            }}
          >
            <Info sx={{ mr: 1, width: 20, height: 20 }} />
            About this stay
          </Typography>
          <Typography color="text.secondary" sx={{ lineHeight: 1.7 }}>
            {hotel.description}
          </Typography>
        </Grid>

        {/* Right: AI Summary Card */}
        <Grid size={{ xs: 12, md: 6 }}>
          <Box
            sx={{
              bgcolor: "#fff",
              p: 4,
              borderRadius: 3,
              border: "1px solid #e5e7eb",
              boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
            }}
          >
            <Typography
              variant="subtitle1"
              sx={{
                display: "flex",
                alignItems: "center",
                fontWeight: 700,
                mb: 2,
                color: "#4f46e5",
              }}
            >
              <Verified sx={{ mr: 1, width: 20, height: 20 }} />
              Guest Sentiment Summary
            </Typography>
            <Typography
              fontStyle="italic"
              fontSize={14}
              color="text.secondary"
              sx={{ lineHeight: 1.6 }}
            >
              "Exceptional service, location, and comfort. Guests love the
              attentive staff and luxurious rooms."
            </Typography>
            <Typography
              fontSize={10}
              mt={2}
              fontWeight={700}
              color="text.secondary"
              textTransform="uppercase"
            >
              Generated by Gemini AI
            </Typography>
          </Box>
        </Grid>
      </Grid>
    </Box>
  );
};
