import { describe, it, expect } from "vitest";
import { screen } from "@testing-library/react";
import "@testing-library/jest-dom";

import { render } from "../../../../test/render";
import { SummarySection } from "./SummarySection";

import { MOCK_HOTELS } from "../../../../constants";

const MOCK_HOTEL = MOCK_HOTELS[0];

const getters = {
  hotelName: () => screen.getByText(MOCK_HOTEL.name),
  location: () => screen.getByText(MOCK_HOTEL.location),
  description: () => screen.getByText(MOCK_HOTEL.description),

  verifiedLuxuryLabel: () =>
    screen.getByText(/verified luxury/i),

  aboutThisStayTitle: () =>
    screen.getByText(/about this stay/i),

  guestSummaryTitle: () =>
    screen.getByText(/guest sentiment summary/i),

  aiGeneratedLabel: () =>
    screen.getByText(/generated by gemini ai/i),

  stars: () => screen.getAllByTestId("StarIcon"),
};

describe("features/hotel/SummarySection", () => {
  describe("Smoke Tests", () => {
    it("renders without crashing", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);
    });
  });

  describe("Rendering", () => {
    it("renders hotel name and location", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);

      expect(getters.hotelName()).toBeInTheDocument();
      expect(getters.location()).toBeInTheDocument();
    });

    it("renders verified luxury label", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);

      expect(getters.verifiedLuxuryLabel()).toBeInTheDocument();
    });

    it("renders correct number of star icons based on rating", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);

      const stars = getters.stars();
      expect(stars).toHaveLength(MOCK_HOTEL.starRating);
    });
  });

  describe("Content Sections", () => {
    it("renders hotel description section", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);

      expect(getters.aboutThisStayTitle()).toBeInTheDocument();
      expect(getters.description()).toBeInTheDocument();
    });

    it("renders AI guest sentiment summary", () => {
      render(<SummarySection hotel={MOCK_HOTEL} />);

      expect(getters.guestSummaryTitle()).toBeInTheDocument();
      expect(getters.aiGeneratedLabel()).toBeInTheDocument();
    });
  });
});
